# -*- coding: utf-8 -*-
"""report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gm9WKl7rAYou_UMp2oV-gOIUfjR2vHKa
"""

import pandas as pd
import datetime
import os

# Create a simple report
date_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
report_path = "/home/ec2-user/daily_report.txt"

content = f"""
--- QUANT PLATFORM DAILY REPORT ---
Date: {date_str}
Status: System running on AWS EC2
Requirement 6: Cron job functional.
Location: {os.getcwd()}
----------------------------------
"""

with open(report_path, "a") as f:
    f.write(content)